image: elixir:1.9

stages:
  - test

day_1:
  stage: test
  script:
    - cd 2019/day1
    - mix deps.get --only-test
    - mix test --cover

day_2:
  stage: test
  script:
    - cd 2019/day2
    - mix deps.get --only-test
    - mix test --cover

day_3:
  stage: test
  script:
    - cd 2019/day3
    - mix deps.get --only-test
    - mix test --cover

day_4:
  stage: test
  script:
    - cd 2019/day4
    - mix deps.get --only-test
    - mix test --cover

day_5:
  stage: test
  script:
    - cd 2019/day5
    - mix deps.get --only-test
    - mix test --cover
