image: elixir:1.9

stages:
  - test

day_1:
  stage: test
  script:
    - cd 2019/day1
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day1/cover
    expire_in: 1 week

day_2:
  stage: test
  script:
    - cd 2019/day2
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day2/cover
    expire_in: 1 week

day_3:
  stage: test
  script:
    - cd 2019/day3
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day3/cover
    expire_in: 1 week

day_4:
  stage: test
  script:
    - cd 2019/day4
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day4/cover
    expire_in: 1 week

day_5:
  stage: test
  script:
    - cd 2019/day5
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day5/cover
    expire_in: 1 week

day_6:
  stage: test
  script:
    - cd 2019/day6
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day6/cover
    expire_in: 1 week

day_7:
  stage: test
  script:
    - cd 2019/day7
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day7/cover
    expire_in: 1 week

day_8:
  stage: test
  script:
    - cd 2019/day8
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day8/cover
    expire_in: 1 week

day_9:
  stage: test
  script:
    - cd 2019/day9
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day9/cover
    expire_in: 1 week

day_10:
  stage: test
  script:
    - cd 2019/day10
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day10/cover
    expire_in: 1 week

day_11:
  stage: test
  script:
    - cd 2019/day11
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day11/cover
    expire_in: 1 week

day_12:
  stage: test
  script:
    - cd 2019/day12
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day12/cover
    expire_in: 1 week

day_13:
  stage: test
  script:
    - cd 2019/day13
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day13/cover
    expire_in: 1 week

day_14:
  stage: test
  script:
    - cd 2019/day14
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day14/cover
    expire_in: 1 week

day_15:
  stage: test
  script:
    - cd 2019/day15
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day15/cover
    expire_in: 1 week

day_16:
  stage: test
  script:
    - cd 2019/day16
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day16/cover
    expire_in: 1 week

day_17:
  stage: test
  script:
    - cd 2019/day17
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day17/cover
    expire_in: 1 week

day_18:
  stage: test
  script:
    - cd 2019/day18
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day18/cover
    expire_in: 1 week
