image: elixir:1.9

stages:
  - test

day_1:
  stage: test
  script:
    - cd 2019/day1
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day1/cover
    expire_in: 1 week

day_2:
  stage: test
  script:
    - cd 2019/day2
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day2/cover
    expire_in: 1 week

day_3:
  stage: test
  script:
    - cd 2019/day3
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day3/cover
    expire_in: 1 week

day_4:
  stage: test
  script:
    - cd 2019/day4
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day4/cover
    expire_in: 1 week

day_5:
  stage: test
  script:
    - cd 2019/day5
    - mix local.hex --force
    - mix deps.get --only-test
    - mix test --cover
  artifacts:
    paths:
      - 2019/day5/cover
    expire_in: 1 week
